config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 1000
      name: Ramp up load
    - duration: 300
      arrivalRate: 1000
      name: Sustained load
  processor:
    "./artilleryIdGeneration.js"
scenarios:
  # We define one scenario:
  - name: "Search"
    flow:
      # Get the details of the product:
      - function: "generateRandomId"
      - get:
          url: "/reviews/api/item/{{ id }}/reviews"
      # Pause for 3 seconds:
      - think: 3
      # - log: "Sent a request to /reviews/api/item/{{ id }}/reviews"